### ISSUE TITLE
Mattermost moving to API version 4

### ISSUE THREAD

**Issue by jasonblais** [altsol/redmine_mattermost#19] opened 2017-02-14 06:02 UTC
Hey @thanosk !

First, hugely appreciate you sharing this project back with the world. Fantastic work!

I wanted to let you know about our plans moving to API v4: 

To make the Mattermost API web service easier to use and to offer more powerful options for these integrations, Mattermost will be moving to a [new API version](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit) soon.  Highlights include:  

* Fully documented API endpoints 
* More in-depth access to server functionality 
* Wider use of established HTTP verbs 
* Consistent endpoint structures 
* A new and improved Go driver  

We plan to release API version 4 on March 16th, with Mattermost server 3.7.  While the current API version 3 will be supported until September 16th, we recommend you begin using API version 4 soon after its release.

#### Contributing  

API version 4 is an active and on-going project. If you're interested in helping contribute, [please join our Mattermost community instance](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and the [APIv4 channel](https://pre-release.mattermost.com/core/channels/apiv4). 

We've prepared a [contribution process for APIv4](https://docs.mattermost.com/developer/api4.html) and a [progress tracker for new APIv4 enpoints](https://docs.google.com/spreadsheets/d/1nPoLgwh_9zRFECpqRUZAKIWihCmX27pnDtFGLtG_WnY/edit#gid=0) to help you get started.

We're also open for suggestions on adding new API endpoints to help with your integration.

**Comment by zx1986** [comment] 2017-08-26 06:29
How to check this error:

```
[2017/08/26 14:25:58 CST] [EROR] /api/v3/teams/zeztzo6jjbdaidtgc1kpfju7xh/channels/djpjet9fo3nhzbcp7afq56deih/posts/create:
Post.IsValid code=500 
rid=to4gf3d617r5jchd6obepocgxw 
uid=1hgprtbhj7fwby6egt1rbafaby 
ip=1.2.3.4 
Invalid message [details: id=9e7s35179jd4myct98o8g6qk4o]
```

**Comment by jasonblais** [comment] 2017-08-27 17:37
@zx1986 Does it come from using this integration?

**Comment by zx1986** [comment] 2017-08-28 03:41
@jasonblais yes, and I had change to use redmine_messenger.

**Comment by jasonblais** [comment] 2017-08-28 21:56
Thanks @zx1986, I see.

Do you know when the error occurs? That'll help us narrow down the potential cause.

**Comment by zx1986** [comment] 2017-08-30 06:40
@jasonblais I can't reproduce it on our server now, 
Redmine with the new plugin had move to production.

**Comment by thanosk** [comment] 2017-09-08 08:24
@zx1986 you would need to provide more debug info in order to trace down your problem.

Other than that, I just tested this plugin with APIv4 and latest mattermost version and it works just fine, so I'm closing this issue until further notice.

**Closed as completed by thanosk** 2017-09-08 08:24 UTC
