### ISSUE TITLE
Update the configuration chapter in the README file

### ISSUE THREAD

**Issue by GuillaumeAmat** [altsol/redmine_mattermost#1] opened 2016-01-18 10:21 UTC
I tried to configure your plugin but can't make it work...
- Where can I find the Mattermost API URL?
- In the per-project configuration, the channel field have to contain the channel's name or a integration url configured in an account?

Anyway, thank you for your work!

**Comment by thanosk** [comment] 2016-01-19 12:11
Hello and thanks for your feedback. I will do my best to update the README file. In the meantime, you can find the Mattermost API URL as follows:

After logging in to Mattermost and your team, create a new incoming webhook for a channel. Click on the dots besides your account in Mattermost (top left) -> Account settings -> Integrations -> Incoming Webhooks -> Add new. After this step, Mattermost is going to create a special URL for you. You can paste/use this URL in Redmine. More information about webhooks is provided here: http://www.mattermost.org/webhooks/

**Comment by GuillaumeAmat** [comment] 2016-01-20 08:33
Oh thank you!
But... ;)
Redmine doesn't seem to call the configured hook. Nothing appears in Mattermost nor the Redmine logs. Any idea?

**Comment by thanosk** [comment] 2016-01-20 09:23
It's generally a multi-step process:

1) In mattermost System console -> Service Settings, make sure icoming webhooks are enabled. You might also want to set the two overriding options (usernames and icons) from webhooks to true, as well.

2) In mattermost Account settings -> Integrations -> Incoming Webhooks, you set-up an incoming hook

3) In Redmine configuration (Administration -> plugins -> Redmine Mattermost) you must set the URL and either a mattermost channel globally, or per project using the custom fields redmine feature.

4) It's equally important to ensure Redmine's network connectivity to Mattermost (i.e. passes through possible NAT/firewalls, etc).

**Comment by GuillaumeAmat** [comment] 2016-01-21 07:46
Thank you again, I really appreciate your help. The three first points were already fine, the fourth too by the way... But Mattermost gives me a 404 when I try to call the hook URL :/

I have to investigate it with the Mattermost folks now ;)

**Comment by GuillaumeAmat** [comment] 2016-01-21 09:07
I found that the hook url works with POST and not GET requests. So the problem is still there...

**Comment by leoniscsem** [comment] 2016-01-21 20:12
Also affected by this. @GuillaumeAmat Have you already opened an issue somewhere? E.g. in their GitHub repo or at their Discourse?

**Comment by GuillaumeAmat** [comment] 2016-01-22 07:17
@leoniscsem Not yet no. I wanted to double check before asking ;)

**Comment by leoniscsem** [comment] 2016-01-22 11:22
I have upgraded the GitLab Omnibus package and it seems no hook is working as intended at all, so there might be some quirks which are not related to this project.

Still I have some problems to understand the configuration of this plugin, especially concerning the channel settings on selected projects. Webhooks generated by Mattermost are channel specific, so how can we use the URL for the API in the general settings and then simply add the channel name to a project?
Next, why do we add the channel name to the hook? When testing with curl, I follow their documentation:
`curl -i -k -X POST -d 'payload={"text": "some text here"}' https://mattermost.domain.tld:port/hooks/<API hash>`

_ignore the -k here, this is just necessary when testing with self-signed certificates_

The `channel name` settings are a Slack thing as far as I understand. When using the Slack Service UI in GitLab for adding the Mattermost hook, the channel name field also is left blank.
[Mattermost Readme](https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md#connecting-mattermost-to-gitlab-using-slack-ui)

**Comment by thanosk** [comment] 2016-01-23 16:44
@GuillaumeAmat this redmine plugin uses POST method for submitting requests to mattermost incoming webhooks. Can you please debug your setup using curl? Like @leoniscsem posted, you can use something like this: `curl -k -X POST -d 'payload={"username": "myusername", "text": "test", "channel": "off-topic"}' https://your-mattermost-domain:port/hooks/API-hash`

@leoniscsem take a look at mattermost's Service settings under System Console. There are two interesting flags: "Enable Overriding Usernames from Webhooks" and "Enable Overriding Icon from Webhooks". They are pretty self-descriptive, you can then use their counterpart payload key, just like I used "username" in the above curl example. Channel override is also provided as is, again check using the "channel" argument in the above JSON payload. This enables you to setup Mattermost and Redmine in the most convenient way: you can either setup redmine to post everything in one channel, or you can instruct each redmine project to post to different channel. The API URL must be provided in the main configuration area in Redmine. If you want Redmine to post everything in one channel, also fill in the channel input field. Otherwise, the per project configuration option is recommended. 
In any case, I will try to provide screenshot-guided instructions in the readme and hope to clarify things up a bit.

**Comment by thanosk** [comment] 2016-01-23 17:33
I've just added new screenshots in the README for clarifying the configuration of this plugin. Let me know if you need extra help, otherwise I think it's ok to close this issue now.

**Comment by leoniscsem** [comment] 2016-01-23 19:59
Thank you for the in-depth explanation. I enabled the overrides as it felt natural to do so, yet the issues persist. I don't know if this is related to the newest roll out of GitLab with Mattermost, so we need to check with them. Great work with the screenshots, helps stupid users like me a lot.

**Comment by thanosk** [comment] 2016-01-23 20:20
Truth be told, I'm testing with a vanilla Mattermost installation, and unfortunatelly I'm a little unaware of what GitLab does. My best guess would be that as long as it reaches the webhook, it should work.

**Comment by leoniscsem** [comment] 2016-01-23 20:25
I assume the issues are related to the GitLab+Mattermost setup and especially to the self signed certificates we are using for testing right now. Now that I have followed your configuration steps I notice the following POST in my Redmine logs:

```
Started POST "/redmine/projects/demoproject/issues" for IP-ADDRESS-HERE at 2016-01-23 21:16:51 +0100
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"totally-secret-hash=", "issue"=>{"is_private"=>"0", "tracker_id"=>"1", "subject"=>"post this now", "description"=>"la la la, checking my log", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"3", "parent_issue_id"=>"", "start_date"=>"2016-01-23", "due_date"=>"2016-01-28", "estimated_hours"=>"1", "done_ratio"=>"0", "watcher_user_ids"=>["52"]}, "commit"=>"Anlegen", "project_id"=>"demoproject"}
```

**Comment by GuillaumeAmat** [comment] 2016-01-25 07:03
@thanosk Awesome you are ;)
My problem was the channel names in the Redmine configuration. I didn't understood that I had to set the « sort of normalized » name which appears in the URL.

Thank you!

**Comment by thanosk** [comment] 2016-01-26 16:26
It's a bit confusing what name a channel gets in Mattermost, the safest way is to look at the screen listing the webhooks.

**Comment by thanosk** [comment] 2016-02-11 13:16
If you disagree with closing this issue, feel free to re-open and discuss.

**Closed as completed by thanosk** 2016-02-11 13:16 UTC
